name: CI/CD Gradle Pipeline

on:
  push:
    branches:
      - main
      - qa
      - preprod
      - prod

jobs:
  # Job for QA Environment
  build-and-test-qa:
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set executable permissions for gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run tests
        run: ./gradlew runWebTests

      - name: Deploy to QA
        env:
          SERVER_URL: ${{ secrets.QA_SERVER_URL }}
          USERNAME: ${{ secrets.QA_USERNAME }}
          PASSWORD: ${{ secrets.QA_PASSWORD }}
        run: |
          echo "Deploying to QA environment"
          # Add deployment commands for QA here

  # Job for Preprod Environment
  build-and-test-preprod:
    if: github.ref == 'refs/heads/preprod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run tests
        run: ./gradlew test

      - name: Deploy to Preprod
        env:
          SERVER_URL: ${{ secrets.PREPROD_SERVER_URL }}
          USERNAME: ${{ secrets.PREPROD_USERNAME }}
          PASSWORD: ${{ secrets.PREPROD_PASSWORD }}
        run: |
          echo "Deploying to Preprod environment"
          # Add deployment commands for Preprod here

  # Job for Production Environment
  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    needs: [build-and-test-qa, build-and-test-preprod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run tests
        run: ./gradlew runWebTests

      - name: Deploy to Production
        env:
          SERVER_URL: ${{ secrets.PROD_SERVER_URL }}
          USERNAME: ${{ secrets.PROD_USERNAME }}
          PASSWORD: ${{ secrets.PROD_PASSWORD }}
        run: |
          echo "Deploying to Production environment!"
          # Add deployment commands for Production here
