name: CI/CD Gradle Pipeline

on:
  push:
    branches:
      - main
      - qa
      - preprod
      - prod

jobs:
  # Job for QA Environment
  run-auto-test-qa:
    name: QA environment pipeline
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest
    env:
      LT_USERNAME: ${{ secrets.LAMBDA_TEST_USERNAME }}
      LT_ACCESS_KEY: ${{ secrets.LAMBDA_TEST_ACCESS_KEY }}
    environment: qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set executable permissions for gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Clean allure results directory
        run: rm -rf ./build/allure-results/*

      - name: Run tests on QA environment with `QA testsuite`
        run: ./gradlew clean runWebRemoteTests
        continue-on-error: true

      - name: Install Allure CLI
        run: |
          curl -sL https://github.com/allure-framework/allure2/releases/download/2.20.1/allure-2.20.1.tgz | tar -xz
          sudo mv allure-2.20.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Verify Allure CLI version
        run: allure --version

      - name: Generate Allure Report for QA environment test run
        run: |
          allure generate ./build/allure-results --clean -o ./build/allure-report

      - name: Upload QA environment Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-qa
          path: ./build/allure-report

      - name: Deploy QA environment Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/allure-report
